[tool.poetry]
name = "zmio"
version = "0.1.0"
description = ""
authors = ["Adam"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"
aima3 = "^1.0.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
